/* msr_table_21.h
 *
 * Model-specific registers selected from table 21 of 
 * Volume 4 of Intel's January 2019 Software Developers' Manual
 * (see https://software.intel.com/en-us/articles/intel-sdm).
 *
 * This file has been generated by generate-headers.py.
 * Probably best to make edits there.
 *
 * Columns are:  tag, name, address, table, scope and bitmask.
 */

#ifndef __PP0_POLICY
#define __PP0_POLICY
_MSR(MSR,PP0_POLICY,0x63A,21,package,0x0)
#endif  //__PP0_POLICY

#ifndef __PP1_ENERGY_STATUS
#define __PP1_ENERGY_STATUS
_MSR(MSR,PP1_ENERGY_STATUS,0x641,21,package,0x0)
#endif  //__PP1_ENERGY_STATUS

#ifndef __PP1_POLICY
#define __PP1_POLICY
_MSR(MSR,PP1_POLICY,0x642,21,package,0x0)
#endif  //__PP1_POLICY

#ifndef __PP1_POWER_LIMIT
#define __PP1_POWER_LIMIT
_MSR(MSR,PP1_POWER_LIMIT,0x640,21,package,0x0)
#endif  //__PP1_POWER_LIMIT

